name = "DualDiff"
uuid = "9c801eb6-d9fb-41a9-8159-de68b1430c15"
authors = ["Pablo Rodríguez Sánchez <pablo.rodriguez.sanchez@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"

[targets]
test = ["Test"]
